name: CB Secret PR Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  SecretScanning:
    uses: REVLOCK/cb-secrets-scanner/.github/workflows/cb-secret-scan.yml@main
    secrets: inherit

